name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/Aircoookie/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        echo '[env:esp32_4CH_DISP_SPI_4mb]' >>platformio.ini
        echo 'extends = env:esp32dev' >>platformio.ini
        echo 'build_flags = ${env:esp32dev.build_flags}
          -D WLED_WATCHDOG_TIMEOUT=0
          -D DATA_PINS=2,4,16,17
          -D PIXEL_COUNTS=100,100,100,100
          -D BTNPIN=-1
          -D RLYPIN=-1
          -D ABL_MILLIAMPS_DEFAULT=9000
          -D USERMOD_FOUR_LINE_DISPLAY
          -D USE_ALT_DISPlAY
          -D FLD_SPI_DEFAULT
          -D FLD_TYPE=SSD1309_SPI64
          -D HW_PIN_SCLKSPI=14
          -D HW_PIN_MOSISPI=13
          -D FLD_PIN_DC=26
          -D FLD_PIN_CS=15
          -D FLD_PIN_RESET=27
          -D USERMOD_ROTARY_ENCODER_UI
          -D ENCODER_DT_PIN=18
          -D ENCODER_CLK_PIN=5
          -D ENCODER_SW_PIN=19
          -D USERMOD_PWM_FAN
          -D PWM_PIN=32
          -D TACHO_PIN=33
          -D USERMOD_MULTI_RELAY
          -D USERMOD_DALLASTEMPERATURE
          -D TEMPERATURE_PIN=25
          -D USERMOD_DALLASTEMPERATURE_MEASUREMENT_INTERVAL=10000
          ' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32dev.lib_deps}' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.35.7' >>platformio.ini
        echo '  https://github.com/blazoncek/OneWire.git' >>platformio.ini

        pio run -e esp32_4CH_DISP_SPI_4mb || pio run -e esp32_4CH_DISP_SPI_4mb
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/esp32_4CH_DISP_SPI_4mb.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/esp32_4CH_DISP_SPI_4mb.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
